#cloud-config
package_update: true
package_upgrade: true

packages:
  - curl
  - python3-pip
  - nginx

runcmd:
 - echo "hello from cloud-init, Chander" > /hello-from-cloud-init.txt
 - systemctl enable nginx
 - systemctl start nginx
 - echo '<h1>Hello from Terraform + cloud-init, Chander ðŸš€</h1>' > /var/www/html/index.nginx-debian.html

